### ISSUE TITLE
StudentTable -> формирование даты

### ISSUE THREAD

**Issue by viktorovich87** [9898mihai/student-list#4]
Почему в этой функции не использовался способ формирования даты с помощью библиотеки `dayjs` ?

https://github.com/9898mihai/student-list/blob/251dd770bdf9793a533acd279789ed53c5886de4/src/components/StudentTable/StudentTable.jsx#L50

**Comment by 9898mihai** [comment]
Сам не знаю, на тот момент я хотел отобразить дату в формате dd/mm/yyyy и сразу пришло в голову сделать в таком формате, но не сделал потому что не получалось, почему то, поменять формат в datepicker и что бы не было два разных формате в таблице и в datepicker то просто поменял перменные дня и месяца местами и забыл. Теперь уже по внимательнее прочитал в документаций как поменять формат в datepicker и уже сформатировал и в таблице. Теперь кода стало поменьше, но пришлось импортировать на одну зависимость больше в компоненте))
