### ISSUE TITLE
Модалка редактирования и добавления студента

### ISSUE THREAD

**Issue by viktorovich87** [9898mihai/student-list#5]
1. Мне разрешается добавить студента с неправильной датой

![image](https://github.com/9898mihai/student-list/assets/35224646/ea5d0921-25f7-43e6-bdd6-dd0d213af809)
2. Если я введу данные при добавлении студента.. а потом закрою модалку - введеная мной информация не сбрасывается и при повторном открытии - показываются старые данные, которые я ввел ранее. 
3. при редактировании студента - я могу сразу сохранить, хотя я ничего не изменял в значениях полей. Желаемое поведение - когда состояние модалки редактирования студента не изменилось, то надо не давать возможность сохранять данные, если я что-то поменял - то кнопка становится активной.. если я поменял что-то и вернул всё обратно - то кнопка должна снова деактивироваться

**Comment by 9898mihai** [comment]
1. исправил
2. исправил
3. Так и было сделано, можете дать больше данных в каких условиях кнопка сразу активна при редактирование?
